### PR TITLE
filter and show rows with missing values

### PR DESCRIPTION
**Pull request by vabarbosa**
#643 
You now have different ways by which you can find/view missing values in a datafarame:
1. The Table view has an option to show all rows, only rows with missing values, on rows without missing values
2. The Filter can now be used to filter rows with missing column values. This can be done by either **(a)** leaving the filter Value field empty or **(b)** entering `None` in the filter Value field

image

### CODE REVIEW

**Comment by vabarbosa** [comment]
@ptitzler

**Comment by DTAIEB** [comment]
@vabarbosa The new combo box is great, but we should be explicit that it operates on the working pandas dataframe which is not necessarily the entire dataset

**Comment by vabarbosa** [comment]
yup, just updated travis

**Comment by vabarbosa** [comment]
@DTAIEB any particular wording/phrasing to use?

**Comment by ptitzler** [comment]
:+1:

**Comment by DTAIEB** [comment]
@vabarbosa perhaps a tooltip message that say
"Warning: this filter only applies to the sampled data and not the original data set"

**Comment by vabarbosa** [comment]
tests have been updated. tooltip has been added.

**Comment by DTAIEB** [comment]
@vabarbosa Reopening because this new feature doesn't work with Spark Dataframe.
Here's the error:
```
2018-03-16 17:09:25,417 - pixiedust.display.display.Display - ERROR - Unexpected error while trying to render BaseChartDisplay
Traceback (most recent call last):
  File "/Users/dtaieb/watsondev/workspaces/cds_workspace/pixiedust-gateway-work/pixiedust/display/chart/renderers/baseChartDisplay.py", line 428, in doRender
    chartFigure = self.doRenderChart()
  File "/Users/dtaieb/watsondev/workspaces/cds_workspace/pixiedust-gateway-work/pixiedust/display/chart/renderers/table/TableDisplay.py", line 14, in doRenderChart
    wpdf = wpdf[wpdf.isna().any(axis=1)]
  File "/Users/dtaieb/anaconda/envs/dashboard/lib/python3.5/site-packages/pandas/core/generic.py", line 3081, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'isna'
```

**Pull request merged**
